### PR TITLE
Wrap biomat checks

### LINKED ISSUE #267: [Tripal3] Warning when using tripal_biomaterial_create_biomaterial
Hello, 

The [tripal_biomaterial_create_biomaterial](https://github.com/tripal/tripal_analysis_expression/blob/master/tripal_biomaterial/api/tripal_biomaterial.api.inc#L606) check the DB for a biomaterial with the same name at the beginning.

Following, several calls are made for the biomaterial parameters, without checking if the DB call actually returned anything.

Would it be possible to wrap this part 
```
 if ($biomaterial_result->taxon_id && $warnings) {
    print("WARNING: Biomaterial with sample_name of '$biomaterial' alreay exists in the database. Overwriting database entries for $biomaterial...\n");
  }
  if ($biomaterial_result->taxon_id and $biomaterial_result->taxon_id != $organism_id) {
    $sql = "SELECT common_name, genus, species FROM {organism} WHERE organism_id = :organism_id";
    $analysis_org = chado_query($sql, [":organism_id" => $organism_id])->fetchObject();
    $biomaterial_org = chado_query($sql, [":organism_id" => $biomaterial_result->taxon_id])->fetchObject();
    print "ERROR: Mismatch between the organism selected in the loader " . "and the organism of a biomaterial in the Chado database.\n" . "  Organism selected by loader: " . $analysis_org->genus . " " . $analysis_org->species . " (" . $analysis_org->common_name . ")\n" . "  Biomaterial organism: " . $biomaterial_org->genus . " " . $biomaterial_org->species . " (" . $biomaterial_org->common_name . ")\n" . "  On biomaterial: " . $biomaterial . "\n" . "Please ensure that the organism selected by the loader " . "and the organism for each biomaterial in the file to be loaded " . "are the same. If these organisms should not be the same, " . "delete the offending biomaterial in Chado or change the name of " . "the biomaterial to another unique name.\n";
    exit;
  }
  $biomaterial_id = $biomaterial_result->biomaterial_id;
  if ($analysis_id) {
    $analysis_name = chado_select_record('analysis', ['name'], ['analysis_id' => $analysis_id]);
  }
  if ($biomaterial_description == '' and $biomaterial_result->description != '') {
    $biomaterial_description = '';
  }
```

In an if(isset($biomaterial_result)) (or something)? That would avoid several warnings about trying to get property of non-object

(Just need to move 
` if ($analysis_id) {
    $analysis_name = chado_select_record('analysis', ['name'], ['analysis_id' => $analysis_id]);
  }` 
out of the loop)

### PR DESCRIPTION
**Pull request by bradfordcondon**
resolves #267 .  Also while I was in there, fix some weird logic and add some comments to clarify whats happening.

### CODE REVIEW

**Comment by bradfordcondon** [comment]
@mboudet do you hae time to check that this PR accomplishes what you want?

**Comment by mboudet** [comment]
Sure, looking into it.

**Comment by mboudet** [comment]
Works fine for me, on both biomaterial creation and update.

Quick question, to make sure it's not related to this PR : I got a warning 
``public://expression/5c6fc1ac191a1_file.matrix could not be added to the analysisprop table because an analysis with id 6 already exists`, which seems to have been added in a recent PR.

Does this means that only one expression file can be linked to one analysis?
Not that it would be a problem, just wanted to clarify.

**Comment by bradfordcondon** [comment]
this wasnt added in this PR.

I think its in there because `analysis_id + type_id + rank` is a unique constraint.  However probably the correct thing to do is to have it insert the prop as an additional rank, rather than prevent adding multiple files to one analysis.

**Comment by bradfordcondon** [comment]
ok, fixed your issue as well @mboudet .  thanks for confirming the original fix.  if the analysisprop problem persists please create an issue, thanks!

**Pull request merged**
