### PR TITLE
added link to download csv

### PR DESCRIPTION
**Pull request by srobb1**
Made some changes to add a download link for CSV. If you are interested in this functionality, maybe you can add an icon for this in that nice list of icons you have at the top of the plot. I use the [Tripaldownload API](https://github.com/tripal/trpdownload_api) and [trpdownload_expression](https://github.com/srobb1/trpdownload_expression)

### CODE REVIEW

**Comment by srobb1** [comment]
I also added the ability to split the input featurenames on spaces or commas

**Comment by almasaeed2010** [comment]
Hello @srobb1,

Sorry for the long delay! We didn't notice the request until now. 

Since the download link is dependent on the Tripal Download API module, which up to this point is in beta, I don't think we should force that dependency.

We appreciate the contribution! We can certainly merge the feature once the download module has a stable release. 

Thanks!

**Comment by srobb1** [comment]
That makes sense!

On Mon, Mar 6, 2017 at 12:12 PM, Abdullah Almsaeed <notifications@github.com

**Comment by bradfordcondon** [comment]
Hi Sofia,

I'm going to close this PR as we've dropped Tripal 2 support, and the new Tripal 3 version supports downloads in a variety of ways.

Is that OK?  If there's a problem we can create a Tripal 2 branch and instate the tripal 2 release onto it, and then you can make this PR to that branch.

Apologies

Bradford

**Comment by srobb1** [comment]
That works. I will just continue to use my code while using T2. Hopefully I
will upgrade to T3 this year... Thanks for all your work on this module!

**Pull request closed without merging**
