### PR TITLE
Updated biosample importer namespace

### PR DESCRIPTION
**Pull request by dsenalik**
This changes the db and cv as discussed in issue #392.

There is something to figure out, though. Several errors as shown below, because the database name of the existing term does not match that of the one provided. There is some commented out code in 
```tripal/tripal_chado/api/modules/tripal_chado.cv.api.inc``` for this case, so nothing happens and the error is triggered. Gotta figure this out...
```
 Tripal_biomaterial  7303  Adds the NCBI biomaterial database and adds the terms to it.  Also moves  terms from the 
                           tripal vocabulary into local.
Do you wish to run all pending updates? (y/n):
ERROR (TRIPAL_CHADO): chado_insert_record; Cannot insert duplicate record into cvterm table: Array
(
    [cv_id] => 58
    [name] => sample_name
    [definition] => Sample Name is a name that you choose for the sample. It can have any format, but we suggest that you make it concise, unique and consistent within your lab, and as informative as possible. Every Sample Name from a single Submitter must be unique.
    [dbxref_id] => 443684
    [is_obsolete] => 0
    [is_relationshiptype] => 0
)

[site http://default] [TRIPAL ERROR] [TRIPAL_CHADO] chado_insert_record; Cannot insert duplicate record into cvterm table: Array(    [cv_id] => 58    [name] => sample_name    [definition] => Sample Name is a name that you choose for the sample. It can have any format, but we suggest that you make it concise, unique and consistent within your lab, and as informative as possible. Every Sample Name from a single Submitter must be unique.    [dbxref_id] => 443684    [is_obsolete] => 0    [is_relationshiptype] => 0)
sizeof(): Parameter must be an array or an object that implements Countable tripal.notice.api.inc:134        [warning]
[site http://default] [TRIPAL WARNING] [TRIPAL_CV] Failed to insert the term: sample_name (local)
...
```

### CODE REVIEW

**Comment by dsenalik** [comment]
I rearranged the order in update 7303 and this eliminated my reported error.

**Comment by dsenalik** [comment]
I have been testing this module in conjuction with tripal_eutils https://github.com/NAL-i5K/tripal_eutils/pull/235 and an Issue I see is that update 7303 only moves four terms from the tripal db to local db, the four terms that it explicitly installs ```['organism', 'sample_name', 'sample_title', 'bioproject_accession']```. I have four terms in the ```biomaterial_property``` cv, tripal db resulting from loading expression data. These are all now present in ```NCBI BioSample Attributes``` cv. I propose doing a lookup for such terms, and adding them to the list of migrated terms.

**Comment by dsenalik** [comment]
Draft documentation changes can be seen at https://github.com/dsenalik/tripal_analysis_expression/tree/ncbi_biosample_space#module-updating

**Comment by spficklin** [comment]
Hey @dsenalik I think the README documentation is good.  I can't easily tell what else is unique because there is now a merge conflict which arose after I merged #392.  Can you fix the conflict and then I'll review once more?

**Review by spficklin — APPROVED** [review]

**Comment by spficklin** [comment]
Looks great!  Thanks :-)

**Comment by spficklin** [comment]
Yes, those were removed because they were used by the loader but the loader was completely rewritten to improve speed.   It's been awhile since I looked at that code so if they are still in use I don't remember why.   I'll create an issue to look at those to make sure.

**Comment by dsenalik** [comment]
My mistake, they are no longer used. I was confused by my branch still had references to them.

**Pull request merged**
